### ISSUE TITLE
Add Delete handler to delete an image on storage

### ISSUE THREAD

**Issue by thoas** [thoas/picfit#4]

**Comment by nsf** [comment]
Hi, may I ask you how you see this feature implemented? And what about deleting cached images on storage as well? I.e. wipe the original images and all associated with it. Is it a bad idea?

**Comment by thoas** [comment]
Excellent question, I'm in phase with your proposal:

* A ``DELETE`` HTTP operation on the image source
* All thumbnails will be deleted too

**Comment by nsf** [comment]
Well, the main question is how? Because as far as I understand you don't track connections between the original image and created/cached ones.

- Original image is in src storage and you can refer to it with its name.
- Then we have a KV store with <hash of all the parameters> key and <filename in dst storage> as a value.
- And the dst storage with cached images.

In order to delete the source image and all of the associated ones we need to keep track of all the connections. That's what I wanted to ask, how you see this implemented? Because your abstraction layer for example doesn't have an "append" operation for KV store. Otherwise we could use it to make a list of images or something like that.

Any thoughts in that regard?

**Comment by thoas** [comment]
As you mentioned, this feature will not be backward compatible for old processed images.

We will have to store each thumbnails hash to a key of the original image in an array for example (It can be done easily with Redis), this abstraction must be reported to [gokvstores](https://github.com/thoas/gokvstores).

**Comment by nsf** [comment]
So, do you mean it's okay for you if I'll add `Append(key string, value interface{}) error` to gokvstores? Because having an atomic "append" is a nice thing to have if we're dealing with lists.

**Comment by thoas** [comment]
:+1: totally, go! :)

**Comment by nsf** [comment]
And the other issue which always concerns me is data races. E.g. what if while we're busy deleting an image and its variants, somebody makes a request for it. Again in DB work you can do locks and other bad things, but in picfit everything is hidden behind relatively simple abstractions. Maybe we can design a deletion process so that it doesn't matter if the request is being made after that?

Just something to think about it.

Okay I'll submit a pull request for "Append" operation soon (maybe today, maybe tomorrow).

**Comment by nsf** [comment]
I'll start working on it how I see it. And then when I have my patches we will talk about it. Maybe you'll have some suggestions.

**Comment by thoas** [comment]
ok, thank you :)
